# coding: utf-8

"""
    Leap Play

    Learn more at https://www.leap-play.com  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import leapplay_client
from leapplay_client.api.stations_api import StationsApi  # noqa: E501
from leapplay_client.rest import ApiException


class TestStationsApi(unittest.TestCase):
    """StationsApi unit test stubs"""

    def setUp(self):
        self.api = leapplay_client.api.stations_api.StationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_station(self):
        """Test case for create_station

        Creates a Station (Auth)  # noqa: E501
        """
        pass

    def test_get_session_logs_all(self):
        """Test case for get_session_logs_all

        Gets closed Sessions from all stations (Auth)  # noqa: E501
        """
        pass

    def test_get_session_logs_by_station_id(self):
        """Test case for get_session_logs_by_station_id

        Gets closed Sessions (Auth)  # noqa: E501
        """
        pass

    def test_get_settings(self):
        """Test case for get_settings

        Gets the Settings of all Stations (Auth)  # noqa: E501
        """
        pass

    def test_get_settings_by_station_id(self):
        """Test case for get_settings_by_station_id

        Get the Settings of an Station (Auth)  # noqa: E501
        """
        pass

    def test_get_state(self):
        """Test case for get_state

        Get the Station's State (Auth)  # noqa: E501
        """
        pass

    def test_get_states(self):
        """Test case for get_states

        Gets Collection of Station States (Auth)  # noqa: E501
        """
        pass

    def test_session_create(self):
        """Test case for session_create

        Creates a Session (Auth)  # noqa: E501
        """
        pass

    def test_session_stop(self):
        """Test case for session_stop

        Stops the running Session (Auth)  # noqa: E501
        """
        pass

    def test_session_update(self):
        """Test case for session_update

        Updates the running Session. (Auth)  # noqa: E501
        """
        pass

    def test_set_settings(self):
        """Test case for set_settings

        Sets the Settings for an Station (Auth)  # noqa: E501
        """
        pass

    def test_set_station_mode(self):
        """Test case for set_station_mode

        Sets the Operation Mode (Auth)  # noqa: E501
        """
        pass

    def test_set_station_password(self):
        """Test case for set_station_password

        Changes the Password (Auth)  # noqa: E501
        """
        pass

    def test_set_station_qr_code(self):
        """Test case for set_station_qr_code

        Sets the QrCode (Auth)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
