# coding: utf-8

"""
    Leap Play

    Learn more at https://www.leap-play.com  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import leapplay_client
from leapplay_client.models.change_request import ChangeRequest  # noqa: E501
from leapplay_client.rest import ApiException


class TestChangeRequest(unittest.TestCase):
    """ChangeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChangeRequest(self):
        """Test ChangeRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = leapplay_client.models.change_request.ChangeRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
