# coding: utf-8

"""
    Leap Play

    Learn more at https://www.leap-play.com  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import leapplay_client
from leapplay_client.models.request_forgot_password import RequestForgotPassword  # noqa: E501
from leapplay_client.rest import ApiException


class TestRequestForgotPassword(unittest.TestCase):
    """RequestForgotPassword unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestForgotPassword(self):
        """Test RequestForgotPassword"""
        # FIXME: construct object with mandatory attributes with example values
        # model = leapplay_client.models.request_forgot_password.RequestForgotPassword()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
