# coding: utf-8

"""
    Leap Play

    Learn more at https://www.leap-play.com  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import leapplay_client
from leapplay_client.models.session_log import SessionLog  # noqa: E501
from leapplay_client.rest import ApiException


class TestSessionLog(unittest.TestCase):
    """SessionLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSessionLog(self):
        """Test SessionLog"""
        # FIXME: construct object with mandatory attributes with example values
        # model = leapplay_client.models.session_log.SessionLog()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
