# coding: utf-8

"""
    Leap Play

    Learn more at https://www.leap-play.com  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import leapplay_client
from leapplay_client.models.request_register_user import RequestRegisterUser  # noqa: E501
from leapplay_client.rest import ApiException


class TestRequestRegisterUser(unittest.TestCase):
    """RequestRegisterUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestRegisterUser(self):
        """Test RequestRegisterUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = leapplay_client.models.request_register_user.RequestRegisterUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
