# coding: utf-8

"""
    Leap Play

    Learn more at https://www.leap-play.com  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import leapplay_client
from leapplay_client.api.auth_api import AuthApi  # noqa: E501
from leapplay_client.rest import ApiException


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self):
        self.api = leapplay_client.api.auth_api.AuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_login(self):
        """Test case for login

        Receive an Access and Refresh Token  # noqa: E501
        """
        pass

    def test_logout(self):
        """Test case for logout

        Invalidate the Refresh token (Auth)  # noqa: E501
        """
        pass

    def test_refresh_token(self):
        """Test case for refresh_token

        Receive a new Access token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
