# coding: utf-8

"""
    Leap Play

    Learn more at https://www.leap-play.com  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import leapplay_client
from leapplay_client.api.accounts_api import AccountsApi  # noqa: E501
from leapplay_client.rest import ApiException


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self):
        self.api = leapplay_client.api.accounts_api.AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_change_password(self):
        """Test case for change_password

        Changes the Password and provides a new Refresh Token (Auth)  # noqa: E501
        """
        pass

    def test_confirm_email(self):
        """Test case for confirm_email

        Confirms ownership of an E-Mail Address by an E-Mail Confirmation Token  # noqa: E501
        """
        pass

    def test_register(self):
        """Test case for register

        Registers a User Account  # noqa: E501
        """
        pass

    def test_request_password(self):
        """Test case for request_password

        Receives a Reset Token that is required to reset the Password  # noqa: E501
        """
        pass

    def test_resend_e_mail_confirmation(self):
        """Test case for resend_e_mail_confirmation

        Re-sends a message with a EMail Confirmation Token.  # noqa: E501
        """
        pass

    def test_reset_password(self):
        """Test case for reset_password

        Resets the Password with an Reset Token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
