# coding: utf-8

"""
    Leap Play

    Learn more at https://www.leap-play.com  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RequestStationQrCode(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'qr_code': 'str'
    }

    attribute_map = {
        'qr_code': 'qrCode'
    }

    def __init__(self, qr_code=None):  # noqa: E501
        """RequestStationQrCode - a model defined in Swagger"""  # noqa: E501

        self._qr_code = None
        self.discriminator = None

        if qr_code is not None:
            self.qr_code = qr_code

    @property
    def qr_code(self):
        """Gets the qr_code of this RequestStationQrCode.  # noqa: E501


        :return: The qr_code of this RequestStationQrCode.  # noqa: E501
        :rtype: str
        """
        return self._qr_code

    @qr_code.setter
    def qr_code(self, qr_code):
        """Sets the qr_code of this RequestStationQrCode.


        :param qr_code: The qr_code of this RequestStationQrCode.  # noqa: E501
        :type: str
        """
        if qr_code is not None and len(qr_code) > 128:
            raise ValueError("Invalid value for `qr_code`, length must be less than or equal to `128`")  # noqa: E501
        if qr_code is not None and len(qr_code) < 1:
            raise ValueError("Invalid value for `qr_code`, length must be greater than or equal to `1`")  # noqa: E501

        self._qr_code = qr_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RequestStationQrCode, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RequestStationQrCode):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
