# coding: utf-8

"""
    Leap Play

    Learn more at https://www.leap-play.com  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RequestRegisterUser(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'username': 'str',
        'e_mail_address': 'str',
        'password': 'str'
    }

    attribute_map = {
        'username': 'username',
        'e_mail_address': 'eMailAddress',
        'password': 'password'
    }

    def __init__(self, username=None, e_mail_address=None, password=None):  # noqa: E501
        """RequestRegisterUser - a model defined in Swagger"""  # noqa: E501

        self._username = None
        self._e_mail_address = None
        self._password = None
        self.discriminator = None

        self.username = username
        self.e_mail_address = e_mail_address
        self.password = password

    @property
    def username(self):
        """Gets the username of this RequestRegisterUser.  # noqa: E501


        :return: The username of this RequestRegisterUser.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this RequestRegisterUser.


        :param username: The username of this RequestRegisterUser.  # noqa: E501
        :type: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501
        if username is not None and len(username) > 30:
            raise ValueError("Invalid value for `username`, length must be less than or equal to `30`")  # noqa: E501
        if username is not None and len(username) < 8:
            raise ValueError("Invalid value for `username`, length must be greater than or equal to `8`")  # noqa: E501

        self._username = username

    @property
    def e_mail_address(self):
        """Gets the e_mail_address of this RequestRegisterUser.  # noqa: E501


        :return: The e_mail_address of this RequestRegisterUser.  # noqa: E501
        :rtype: str
        """
        return self._e_mail_address

    @e_mail_address.setter
    def e_mail_address(self, e_mail_address):
        """Sets the e_mail_address of this RequestRegisterUser.


        :param e_mail_address: The e_mail_address of this RequestRegisterUser.  # noqa: E501
        :type: str
        """
        if e_mail_address is None:
            raise ValueError("Invalid value for `e_mail_address`, must not be `None`")  # noqa: E501
        if e_mail_address is not None and len(e_mail_address) > 100:
            raise ValueError("Invalid value for `e_mail_address`, length must be less than or equal to `100`")  # noqa: E501
        if e_mail_address is not None and len(e_mail_address) < 6:
            raise ValueError("Invalid value for `e_mail_address`, length must be greater than or equal to `6`")  # noqa: E501

        self._e_mail_address = e_mail_address

    @property
    def password(self):
        """Gets the password of this RequestRegisterUser.  # noqa: E501


        :return: The password of this RequestRegisterUser.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this RequestRegisterUser.


        :param password: The password of this RequestRegisterUser.  # noqa: E501
        :type: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501
        if password is not None and len(password) > 80:
            raise ValueError("Invalid value for `password`, length must be less than or equal to `80`")  # noqa: E501
        if password is not None and len(password) < 10:
            raise ValueError("Invalid value for `password`, length must be greater than or equal to `10`")  # noqa: E501

        self._password = password

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RequestRegisterUser, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RequestRegisterUser):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
